### ISSUE TITLE
What is the License of the whole project?

### ISSUE THREAD

**Issue by aokomoriuta** [gavlinski/Foursquare-Mass-Editor-Tools#1]
HI, thank you for developing good tools!
This is a feature request.

I want to make some little pull-requests.
But currently there is only license specification about the php files, thus I can not fork your repository neither make my contribution public because non-php files are not speficfied their license.

Can you specify this tool's license?
If you are not experienced with Free/Open Licenses, [GitHub's official page](https://help.github.com/en/articles/licensing-a-repository) would helps you.

thanks

**Comment by gavlinski** [comment]
Hi, thank you for your suggestion. I've licensed the entire project under GPLv3.
Please take a look and tell me if everything is right now.

Any kind of contribution will be really appreciated.

**Comment by aokomoriuta** [comment]
Thanks you for commits! I think it's OK now.
